name: Python Uygulama Testi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Testleri çalıştır
        run: |
          pytest
